name: THREEGON
favicon: null
layout_spectrum: 0.5094115699175745
typography_spectrum: 0.5503642056137323
title: OEM manufacturing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.022829440189525485
  lightness: 0.7249120306223631
  saturation: 0.9405096862465143
  rhythmicContrast: 0.52226966409944
purpose: []
