name: THREEGON
favicon: null
layout_spectrum: 0.5094115699175745
typography_spectrum: 0.5503642056137323
title: OEM manufacturing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#bcc9d9'
    - '#7195af'
    - '#484848'
  brandStrength: 0.022829440189525485
  lightness: 0.7249120306223631
  saturation: 0.9405096862465143
  rhythmicContrast: 0.52226966409944
purpose: []
